logging:
  level:
    root: info
    app.sample.messages.filter.AuditingFilter: debug
    org.hibernate.SQL: debug

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_messages?useSSL=false
    username: study
    password: study
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true